[manifest]
version = "1.1.1"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "obj/notes/Block.lua"
pattern = '''
self.inverse = false
'''
position = "after"
payload = '''
if extrasavedata.allInverse then
	self.inverse = true
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/notes/Block.lua"
pattern = '''
self.tap = self.tap or false
'''
position = "after"
payload = '''
if extrasavedata.allTap then
	self.tap = true
end
'''
match_indent = true