[manifest]
version = "1.1.1"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = '''
MeterY = 50 
'''
position = "at"
payload = '''
MeterY = 50 + mods["DetailedAcc"].config.MeterYOffset or 0
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = '''
drawX = 28
'''
position = "at"
payload = '''
drawX = 3
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = '''
print("hi cerdef")
'''
position = "after"
payload = '''
print("hi tgtm")
'''
match_indent = true
