[manifest]
version = "1.1.1"
dump_lua = true
priority = 0

#If you are looking for alwaysNegativeScrollSpeed, it is in gamemanager_misc.toml - cerdef for cerdef and whomever got lost here

# NOTE MODIFIERS

[[patches]]
[patches.pattern]
target = "obj/notes/Block.lua"
pattern = '''
self.inverse = false
'''
position = "after"
payload = '''
if extrasavedata.allInverse then
	self.inverse = true
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "levelformat/events/Notes/bounce.lua"
pattern = '''
tap = event.tap,
'''
position = "at"
payload = '''
tap = event.tap or extrasavedata.allTap,
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "levelformat/events/Notes/block.lua"
pattern = '''
tap = event.tap,
'''
position = "at"
payload = '''
tap = event.tap or extrasavedata.allTap,
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "levelformat/events/Notes/inverse.lua"
pattern = '''
tap = event.tap,
'''
position = "at"
payload = '''
tap = event.tap or extrasavedata.allTap,
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "levelformat/events/Notes/side.lua"
pattern = '''
tap = event.tap,
'''
position = "at"
payload = '''
tap = event.tap or extrasavedata.allTap,
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "levelformat/events/Notes/hold.lua"
pattern = '''
tap = event.startTap,
endTap = event.endTap,
'''
position = "at"
payload = '''
tap = event.startTap or extrasavedata.allTap,
endTap = event.endTap or extrasavedata.allTap,
'''
match_indent = true

# PLAYER MODIFIERS

[[patches]]
[patches.pattern]
target = "obj/Player.lua"
pattern = '''
function Player:getDistance()
'''
position = "before"
payload = '''
function Player:arrowKey()
    local x, y = 0, 0

    if maininput:down("kp8") or maininput:down("up") then    -- up
        y = y - 1
    end
    if maininput:down("kp2") or maininput:down("down") then    -- down
        y = y + 1
    end
    if maininput:down("kp6") or maininput:down("right") then    -- right
        x = x + 1
    end
    if maininput:down("kp4") or maininput:down("left") then    -- left
        x = x - 1
    end

    if maininput:down("kp7") then    -- up-left
        x = x - 1
        y = y - 1
    end
    if maininput:down("kp9") then    -- up-right
        x = x + 1
        y = y - 1
    end
    if maininput:down("kp1") then    -- down-left
        x = x - 1
        y = y + 1
    end
    if maininput:down("kp3") then    -- down-right
        x = x + 1
        y = y + 1
    end

    if x ~= 0 or y ~= 0 then
        local angle = math.deg(math.atan2(x, -y))
        if angle < 0 then
            angle = angle + 360
        end

        self.angle = angle
    end
end

'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/Player.lua"
pattern = '''
local angleDifference = self.angle - self.anglePrevFrame
'''
position = "before"
payload = '''
end
if extrasavedata.arrowKeyControls then
	self:arrowKey()
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/Player.lua"
pattern = '''
for k, v in ipairs(self.angleHistory) do
					if v[1] < cs.cBeat - 5 then
						table.remove(self.angleHistory, k)
					end
				end
			end
		end
'''
position = "after"
payload = '''
if not (extrasavedata.onlyArrowKeys and extrasavedata.arrowKeyControls) then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/Player.lua"
pattern = '''
function Player:update(dt)
  prof.push("player update")
'''
position = "after"
payload = '''
if extrasavedata.movesTowardsMouse then
    local dx = self.x - mouse.rx
    local dy = self.y - mouse.ry
    local distance = math.sqrt(dx*dx + dy*dy)
    
    if distance > extrasavedata.moveToRadiusCranky then
        local angle = math.atan2(dy, dx)
        local targetX = mouse.rx + math.cos(angle) * extrasavedata.moveToRadiusCranky
        local targetY = mouse.ry + math.sin(angle) * extrasavedata.moveToRadiusCranky
        flux.to(self, extrasavedata.crankySpeedToMouse or 5, {x = targetX, y = targetY}):ease("inOutQuad")
    end
end
'''
match_indent = true

# RESULTS SCREEN

[[patches]]
[patches.pattern]
target = "states/Game.lua"
pattern = '''
cs.maxCombo = self.maxCombo
'''
position = "after"
payload = '''
cs.gotJumpscared = self.gotJumpscared
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Results.lua"
pattern = '''savedata.costumes.currentCostume == "jolly" or'''
position = "before"
payload = '''
extrasavedata.playingCrank or
extrasavedata.movesTowardsMouse or
extrasavedata.arrowKeyControls or
extrasavedata.onlyArrowKeys or
extrasavedata.robloxAds or
extrasavedata.allInverse or
extrasavedata.allTap or
extrasavedata.alwaysNegativeSC or
cs.gotJumpscared or
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Results.lua"
pattern = '''if savedata.options.accessibility.taps ~= 'default' then'''
position = "before"
payload = '''
if extrasavedata.playingCrank then
	if str ~= '' then str = str .. ', ' end
	str = str .. loc.get('extrastuffCrankPlays')
end
if extrasavedata.movesTowardsMouse then
	if str ~= '' then str = str .. ', ' end
	str = str .. loc.get('extrastuffMoveTowardMouse')
end
if extrasavedata.robloxAds then
	if str ~= '' then str = str .. ', ' end
	str = str .. loc.get('extrastuffHasAds')
end
if extrasavedata.onlyArrowKeys then
	if str ~= '' then str = str .. ', ' end
	str = str .. loc.get('extrastuffOnlyArrowKey')
elseif extrasavedata.arrowKeyControls then
	if str ~= '' then str = str .. ', ' end
	str = str .. loc.get('extrastuffArrowKey')
end
if extrasavedata.allInverse then
	if str ~= '' then str = str .. ', ' end
	str = str .. loc.get('extrastuffInversed')
end
if extrasavedata.allTap then
	if str ~= '' then str = str .. ', ' end
	str = str .. loc.get('extrastuffAllTaps')
end
if extrasavedata.alwaysNegativeSC then
	if str ~= '' then str = str .. ', ' end
	str = str .. loc.get('extrastuffNegativeSC')
end
if cs.gotJumpscared then
	if str ~= '' then str = str .. ', ' end
	str = str .. loc.get('extrastuffGotJumpscared', {string.format(cs.gotJumpscared, "%f")})
end
--print(fonts.digitalDisco:getHeight())
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Results.lua"
pattern = '''
color()
love.graphics.polygon('fill',trapezoid)
color(1)
love.graphics.polygon('line',trapezoid)
love.graphics.print(str, 600 - textWidth - 5, project.res.y - 18 + (35 * self.zoomIn))
'''
position = "at"
payload = '''
--print(str)
if textWidth > 500 then
    local padding = { x = 10, y = 3 }
    local limit = 500
    local rows = math.ceil(textWidth / limit)
    local topY = project.res.y - 19 + (35 * self.zoomIn) - (rows * textHeight/2)
    local bottomY = project.res.y +  1 + (35 * self.zoomIn)
    local trapezoid = {
        602, topY,     -- point 1
        600 - 510, topY,     -- point 2
        600 - 530, bottomY,  -- point 3
        602, bottomY,  -- point 4
    }
    color()
    love.graphics.polygon('fill', trapezoid)
    color(1)
    love.graphics.polygon('line', trapezoid)
    love.graphics.printf(str, 590 - limit, topY + padding.y, limit, "right")
else
	color()
	love.graphics.polygon('fill',trapezoid)
	color(1)
	love.graphics.polygon('line',trapezoid)
	love.graphics.print(str, 600 - textWidth - 5, project.res.y - 18 + (35 * self.zoomIn))
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Results.lua"
pattern = '''
			local trapezoid = {
				602, 					project.res.y - 19 + (35 * self.zoomIn),		-- point 1
				600 - (textWidth+10), 	project.res.y - 19 + (35 * self.zoomIn),		-- point 2
				600 - (textWidth+30), 	project.res.y +  1 + (35 * self.zoomIn),		-- point 3
				602, 					project.res.y +  1 + (35 * self.zoomIn),		-- point 4
			}'''
position = "before"
payload = '''
local textHeight = fonts.digitalDisco:getHeight()

local padding = { x = 10, y = 3 }

trapezoid = {
    602,                        project.res.y - (textHeight + padding.y) + (35 * self.zoomIn),  -- point 1
    600 - (textWidth+10),       project.res.y - (textHeight + padding.y) + (35 * self.zoomIn),  -- point 2
    600 - (textWidth+30),       project.res.y +  padding.y               + (35 * self.zoomIn),  -- point 3
    602,                        project.res.y +  padding.y               + (35 * self.zoomIn),  -- point 4
}
'''
match_indent = true

