[manifest]
version = "1.1.1"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "states/SongSelect.lua"
pattern = '''
st:setUpdate(function(self,dt)
'''
position = "after"
payload = '''
local function chooseItem()
	local choice
	for i = 1, #self.menuItems do
        local idx = math.random(1, #self.menuItems)
        local item = self.menuItems[idx]

        if item.isLevel or (extrasavedata.allowRandomLevelFolder and not item.isLevel and 
			not item.isMarathon and 
			not item.openCustomsFolder and 
			not item.editor and 
			not item.quitToMenu) then
            choice = idx
            break
        end
    end
	return choice
end

--print(helpers.dumpTable(self.menuItems[self.selection]), "wow")
if extrasavedata.randomLevelButton and maininput:released("r") then
    local choice = chooseItem()

    if choice then
        self.selection = choice
        te.play(sounds.click, "static", "sfx", 0.5)

        self.listEase = flux.to(self,30,{easedSelection=self.selection}):ease("outExpo")
        self:updateSelection()
        self:resetLevelPreload()
        self.rateMod = 1.0
        if cs.source then cs.source:setPitch(1.0) end
		
		local accept = not self.menuItems[self.selection].isLevel and 
			not self.menuItems[self.selection].isMarathon and 
			not self.menuItems[self.selection].openCustomsFolder and 
			not self.menuItems[self.selection].editor and 
			not self.menuItems[self.selection].quitToMenu
        if accept then
            maininput:forceInput('accept', 1)
			chooseItem()
        end
    end
end

'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/SongSelect.lua"
pattern = '''
function st:editLevel(filename,newLevel)
'''
position = "after"
payload = '''
local function loadEditor()
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/SongSelect.lua"
pattern = '''
returnData = {state = 'SongSelect', vars = {topDirectory = self.topDirectory, currentDirectory = self.currentDirectory,
		selection = self.selection, subfolderSelections = self.subfolderSelections, allowEditor = self.allowEditor}}
	

	cs:init()
'''
position = "after"
payload = '''
end

if self.menuItems[self.selection].isLevel and self.menuItems[self.selection].rawMetadata.formatversion and self.menuItems[self.selection].rawMetadata.formatversion > 14 and extrasavedata.openDemoLevelWarning then
	loadEditor()
elseif self.menuItems[self.selection].isLevel and extrasavedata.openDemoLevelWarning then
	
	PopupManager.queuePopup('This is a\nDemo level', '\n\nWould you still like \nto open it?', 60, {
		{label='popupYes',func = function()
			loadEditor()
		end},
		{label='popupNo',func = function() 
			
		end}
	})
else
	loadEditor()
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/SongSelect.lua"
pattern = '''
function st:playLevel(filename, variant)
'''
position = "after"
payload = '''
if PopupManager.queue[1] then
	PopupManager:close()
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/SongSelect.lua"
pattern = '''
self.sortingButton = em.init('SortingButton',{x = project.res.cx, y = project.res.cy })
'''
position = "after"
payload = '''
if extrasavedata.showTags then
	self.tagsDisplay = em.init('TagsDisplay',{ x = 590, y = 10 })
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/SongSelect.lua"
pattern = '''
self.levelData = levelData -- Loads the level data in memory so it can be fed to the level upon load. This is probably a very minor performance improvement, but we're already pre-loading the data so might as well.
'''
position = "after"
payload = '''
if extrasavedata.showTags then
local tagList = tags.generateTags(self.levelData, true)
self.tagsDisplay:setTags(tagList)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/SongSelect.lua"
pattern = '''
self.sortingButton:update(dt)
'''
position = "after"
payload = '''
if extrasavedata.showTags then
self.tagsDisplay:update(dt)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/SongSelect.lua"
pattern = '''
self.sortingButton:draw(-(self.x+1) * 350)
'''
position = "after"
payload = '''
if extrasavedata.showTags then
self.tagsDisplay:draw()
end
'''
match_indent = true
[[patches]]
[patches.pattern]
target = "states/SongSelect.lua"
pattern = '''
love.graphics.printf(level.bpm,xBorder+xOffset,bpmY,wrapLimit,'left')
'''
position = "at"
payload = '''
local str = level.bpm
local length = 0
local FC = 0
if extrasavedata.chartinfoplus and extrasavedata.chartinfoplus.enabled then
	if self.levelData and self.timingInfo then
		if extrasavedata.chartinfoplus.levelLength then
			length = tags.calculateLevelLength(self.timingInfo)
			str = str .. " Len: " .. tostring(math.floor(length/60)) .. ":" .. tostring(string.format("%02d", math.floor(length%60)))
		end
		if extrasavedata.chartinfoplus.fullCombo then
			FC = tags.getFullCombo(self.levelData)
			str = str .. " FC: " .. FC
		end
	else
		if extrasavedata.chartinfoplus.levelLength then
			str = str .. " Len: ??:??"
		end
		if extrasavedata.chartinfoplus.fullCombo then
			str = str .. " FC: ???"
		end
	end
end

love.graphics.printf(str,xBorder+xOffset,bpmY,wrapLimit + 200,'left')
'''
match_indent = true

#[[patches]]
#[patches.pattern]
#target = "states/SongSelect.lua"
#pattern = '''
#cs = bs.load('Game')
#'''
#position = "after"
#payload = '''
#self.levelData.properties.songChoice = self.songChoice
#'''
#match_indent = true
