[manifest]
version = "1.1.1"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "states/SongSelect.lua"
pattern = '''
function st:editLevel(filename,newLevel)
'''
position = "after"
payload = '''
local function loadEditor()
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/SongSelect.lua"
pattern = '''
returnData = {state = 'SongSelect', vars = {topDirectory = self.topDirectory, currentDirectory = self.currentDirectory,
		selection = self.selection, subfolderSelections = self.subfolderSelections, allowEditor = self.allowEditor}}
	

	cs:init()
'''
position = "after"
payload = '''
end

if self.menuItems[self.selection].isLevel and self.menuItems[self.selection].rawMetadata.formatversion and self.menuItems[self.selection].rawMetadata.formatversion > 14 and extrasavedata.openDemoLevelWarning then
	loadEditor()
elseif self.menuItems[self.selection].isLevel and extrasavedata.openDemoLevelWarning then
	
	PopupManager.queuePopup('This is a\nDemo level', '\n\nWould you still like \nto open it?', 60, {
		{label='popupYes',func = function()
			loadEditor()
		end},
		{label='popupNo',func = function() 
			
		end}
	})
else
	loadEditor()
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/SongSelect.lua"
pattern = '''
function st:playLevel(filename, variant)
'''
position = "after"
payload = '''
if PopupManager.queue[1] then
	PopupManager:close()
end
'''
match_indent = true
